services:
  backend:
    build:
      context: ./services/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    env_file:
      - .env
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - ./services/backend/app:/app
      # - ./services/backend/app:/test
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5001 --loop asyncio
    depends_on:
      - test_db
    
  frontend:
      build: ./services/frontend
      volumes:
        - ./services/frontend:/usr/src/app
      ports:
        - 5174:5174
      command: yarn dev --host 0.0.0.0 --port 5174
      depends_on:
        - backend

  test_db:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/

volumes:
  postgres_data_test:
